name: block-guard
description: makes it possible to protect players blocks in case of an attempt to destroy them.
version: 1.0
author: Salatosik
api-version: 1.12
main: me.salatosik.blockguardplugin.Main

commands:
  give-block-picker:
    description: Gives the magic stick
    usage: /command
    aliases:
      - gbp

  disable-block-adding:
    description: Disables the automatic addition of delivered blocks to the database
    usage: /command <disable|enable>
    aliases:
      - dbd

  give-guard-remover:
    description: Removes block protection
    usage: /command
    aliases:
      - ggr

  give-guard-addition:
    description: Gives an item that when clicked on a block gives protection
    usage: /command
    aliases:
      - gga